### ISSUE TITLE
v0.2 Tracking Issue

### ISSUE THREAD

**Issue by flosse** [coop-care/org#8]
- [ ] Name #1
- [ ] Website #4
- [ ] CLA #6 
- [ ] Register Form
- [ ] translation of Omaha System terminology (symptoms, descriptions)
- [ ] chart design
- [ ] plausibility checks and warnings
- [ ] action: prioritise low priority problem
- [ ] action: add further interventions
- [ ] action: end ongoing intervention
- [ ] action: archive customer
- [ ] action: mark problem as resolved
- [ ] tree components: highlight search term, expand nodes for selected items
